[package]
name = "markdown-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.3"
glob = "0.3"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
chrono = "0.4"
